name: grafium
favicon: null
layout_spectrum: 0.2835223670117557
typography_spectrum: 0.8834975936915725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcbd00'
    - '#5a4c4c'
    - '#cf1b00'
    - '#fe702e'
  brandStrength: 0.2924770968966186
  lightness: 0.3907955789472908
  saturation: 0.07548795244656503
  rhythmicContrast: 0.10620538215152919
purpose: []
