name: grafium
favicon: null
layout_spectrum: 0.50183
typography_spectrum: 0.57299
title: grafium.grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#3b3733'
    - '#88a59c'
    - '#216d89'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
