name: grafium
favicon: null
layout_spectrum: 0.25111
typography_spectrum: 0.57299
title: grafium.grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcbd00'
    - '#5a4c4c'
    - '#cf1b00'
    - '#fe702e'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
